In [122]:
import pandas as pd
import numpy as np
import scipy as sci
from decimal import *
import matplotlib.pyplot as plt

In [123]:
df = pd.read_csv('SpotifyFeatures.csv')

In [124]:
df

genre               artist_name                        track_name  \
0       Movie            Henri Salvador       C'est beau de faire un Show   
1       Movie         Martin & les fées  Perdu d'avance (par Gad Elmaleh)   
2       Movie           Joseph Williams    Don't Let Me Be Lonely Tonight   
3       Movie            Henri Salvador    Dis-moi Monsieur Gordon Cooper   
4       Movie              Fabien Nataf                         Ouverture   
...       ...                       ...                               ...   
232720   Soul                     Slave                      Son Of Slide   
232721   Soul  Jr Thomas & The Volcanos                      Burning Fire   
232722   Soul              Muddy Waters    (I'm Your) Hoochie Coochie Man   
232723   Soul                   R.LUM.R                     With My Words   
232724   Soul            Mint Condition    You Don't Have To Hurt No More   

                      track_id  popularity  acousticness  danceability  \
0       0BRjO6ga9RKCKjfDqeFgWV           0       0.61100         0.389   
1       0BjC1NfoEOOusryehmNudP           1       0.24600         0.590   
2       0CoSDzoNIKCRs124s9uTVy           3       0.95200         0.663   
3       0Gc6TVm52BwZD07Ki6tIvf           0       0.70300         0.240   
4       0IuslXpMROHdEPvSl1fTQK           4       0.95000         0.331   
...                        ...         ...           ...           ...   
232720  2XGLdVl7lGeq8ksM6Al7jT          39       0.00384         0.687   
232721  1qWZdkBl4UVPj9lK6HuuFM          38       0.03290         0.785   
232722  2ziWXUmQLrXTiYjCg2fZ2t          47       0.90100         0.517   
232723  6EFsue2YbIG4Qkq8Zr9Rir          44       0.26200         0.745   
232724  34XO9RwPMKjbvRry54QzWn          35       0.09730         0.758   

        duration_ms  energy  instrumentalness key  liveness  loudness   mode  \
0             99373   0.910          0.000000  C#    0.3460    -1.828  Major   
1            137373   0.737          0.000000  F#    0.1510    -5.559  Minor   
2            170267   0.131          0.000000   C    0.1030   -13.879  Minor   
3            152427   0.326          0.000000  C#    0.0985   -12.178  Major   
4             82625   0.225          0.123000   F    0.2020   -21.150  Major   
...             ...     ...               ...  ..       ...       ...    ...   
232720       326240   0.714          0.544000   D    0.0845   -10.626  Major   
232721       282447   0.683          0.000880   E    0.2370    -6.944  Minor   
232722       166960   0.419          0.000000   D    0.0945    -8.282  Major   
232723       222442   0.704          0.000000   A    0.3330    -7.137  Major   
232724       323027   0.470          0.000049  G#    0.0836    -6.708  Minor   

        speechiness    tempo time_signature  valence  
0            0.0525  166.969            4/4    0.814  
1            0.0868  174.003            4/4    0.816  
2            0.0362   99.488            5/4    0.368  
3            0.0395  171.758            4/4    0.227  
4            0.0456  140.576            4/4    0.390  
...             ...      ...            ...      ...  
232720       0.0316  115.542            4/4    0.962  
232721       0.0337  113.830            4/4    0.969  
232722       0.1480   84.135            4/4    0.813  
232723       0.1460  100.031            4/4    0.489  
232724       0.0287  113.897            4/4    0.479  

[232725 rows x 18 columns]

In [125]:
df1 = df
df1.drop(["artist_name", "track_name","track_id","key","mode","time_signature"], axis = 1, inplace = True)
df1

genre  popularity  acousticness  danceability  duration_ms  energy  \
0       Movie           0       0.61100         0.389        99373   0.910   
1       Movie           1       0.24600         0.590       137373   0.737   
2       Movie           3       0.95200         0.663       170267   0.131   
3       Movie           0       0.70300         0.240       152427   0.326   
4       Movie           4       0.95000         0.331        82625   0.225   
...       ...         ...           ...           ...          ...     ...   
232720   Soul          39       0.00384         0.687       326240   0.714   
232721   Soul          38       0.03290         0.785       282447   0.683   
232722   Soul          47       0.90100         0.517       166960   0.419   
232723   Soul          44       0.26200         0.745       222442   0.704   
232724   Soul          35       0.09730         0.758       323027   0.470   

        instrumentalness  liveness  loudness  speechiness    tempo  valence  
0               0.000000    0.3460    -1.828       0.0525  166.969    0.814  
1               0.000000    0.1510    -5.559       0.0868  174.003    0.816  
2               0.000000    0.1030   -13.879       0.0362   99.488    0.368  
3               0.000000    0.0985   -12.178       0.0395  171.758    0.227  
4               0.123000    0.2020   -21.150       0.0456  140.576    0.390  
...                  ...       ...       ...          ...      ...      ...  
232720          0.544000    0.0845   -10.626       0.0316  115.542    0.962  
232721          0.000880    0.2370    -6.944       0.0337  113.830    0.969  
232722          0.000000    0.0945    -8.282       0.1480   84.135    0.813  
232723          0.000000    0.3330    -7.137       0.1460  100.031    0.489  
232724          0.000049    0.0836    -6.708       0.0287  113.897    0.479  

[232725 rows x 12 columns]

LABEL ENCODING - "GENRE"

In [126]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [127]:
df1['genre'] = label_encoder.fit_transform(df1['genre'])

FEATURE SCALING MINMAX SCALE

In [128]:
from sklearn.preprocessing import MinMaxScaler
array = df1.values
x = array[:,0:11]
y = array[:,11]
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(x)
np.set_printoptions(precision=3)
rescaledX[:,:]

array([[0.577, 0.   , 0.613, ..., 0.901, 0.032, 0.643],
       [0.577, 0.01 , 0.247, ..., 0.834, 0.068, 0.676],
       [0.577, 0.03 , 0.956, ..., 0.686, 0.015, 0.325],
       ...,
       [0.923, 0.47 , 0.905, ..., 0.786, 0.133, 0.253],
       [0.923, 0.44 , 0.263, ..., 0.806, 0.131, 0.328],
       [0.923, 0.35 , 0.098, ..., 0.814, 0.007, 0.393]])

FEATURE SCALING STANDARD SCALE

In [129]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(x)
rescaledX = scaler.transform(x)
rescaledX[:,:]

array([[ 0.184, -2.261,  0.683, ...,  1.291, -0.368,  1.596],
       [ 0.184, -2.206, -0.345, ...,  0.669, -0.183,  1.823],
       [ 0.184, -2.096,  1.645, ..., -0.718, -0.456, -0.588],
       ...,
       [ 1.385,  0.323,  1.501, ...,  0.215,  0.147, -1.085],
       [ 1.385,  0.158, -0.3  , ...,  0.406,  0.136, -0.571],
       [ 1.385, -0.337, -0.765, ...,  0.477, -0.496, -0.122]])

FEATURE SCALING NORMALIZER

In [130]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(x)
normalizedX=scaler.transform(x)
normalizedX[:,:]

array([[ 1.509e-04,  0.000e+00,  6.149e-06, ..., -1.840e-05,  5.283e-07,
         1.680e-03],
       [ 1.092e-04,  7.279e-06,  1.791e-06, ..., -4.047e-05,  6.319e-07,
         1.267e-03],
       [ 8.810e-05,  1.762e-05,  5.591e-06, ..., -8.151e-05,  2.126e-07,
         5.843e-04],
       ...,
       [ 1.437e-04,  2.815e-04,  5.397e-06, ..., -4.960e-05,  8.864e-07,
         5.039e-04],
       [ 1.079e-04,  1.978e-04,  1.178e-06, ..., -3.208e-05,  6.564e-07,
         4.497e-04],
       [ 7.430e-05,  1.084e-04,  3.012e-07, ..., -2.077e-05,  8.885e-08,
         3.526e-04]])

FEATURE SCALING BINARIZER

In [131]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(x)
binaryX = binarizer.transform(x)
binaryX[:,:]

array([[1., 0., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.]])

In [132]:
df1

genre  popularity  acousticness  danceability  duration_ms  energy  \
0          15           0       0.61100         0.389        99373   0.910   
1          15           1       0.24600         0.590       137373   0.737   
2          15           3       0.95200         0.663       170267   0.131   
3          15           0       0.70300         0.240       152427   0.326   
4          15           4       0.95000         0.331        82625   0.225   
...       ...         ...           ...           ...          ...     ...   
232720     24          39       0.00384         0.687       326240   0.714   
232721     24          38       0.03290         0.785       282447   0.683   
232722     24          47       0.90100         0.517       166960   0.419   
232723     24          44       0.26200         0.745       222442   0.704   
232724     24          35       0.09730         0.758       323027   0.470   

        instrumentalness  liveness  loudness  speechiness    tempo  valence  
0               0.000000    0.3460    -1.828       0.0525  166.969    0.814  
1               0.000000    0.1510    -5.559       0.0868  174.003    0.816  
2               0.000000    0.1030   -13.879       0.0362   99.488    0.368  
3               0.000000    0.0985   -12.178       0.0395  171.758    0.227  
4               0.123000    0.2020   -21.150       0.0456  140.576    0.390  
...                  ...       ...       ...          ...      ...      ...  
232720          0.544000    0.0845   -10.626       0.0316  115.542    0.962  
232721          0.000880    0.2370    -6.944       0.0337  113.830    0.969  
232722          0.000000    0.0945    -8.282       0.1480   84.135    0.813  
232723          0.000000    0.3330    -7.137       0.1460  100.031    0.489  
232724          0.000049    0.0836    -6.708       0.0287  113.897    0.479  

[232725 rows x 12 columns]

In [133]:
X = df1.drop("genre",axis = 1)
y = df1["genre"]

In [134]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(x,y,test_size=0.30)
print(X_train.shape, X_test.shape, y_train.shape,y_test.shape)

(162907, 11) (69818, 11) (162907,) (69818,)


In [135]:
# evaluation of a model using all features chosen with mutual information
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# feature selection
def select_features(X_train, y_train, X_test):
	# configure to select a subset of features
	fs = SelectKBest(score_func=mutual_info_regression, k='all')
	# learn relationship from training data
	fs.fit(X_train, y_train)
	# transform train input data
	X_train_fs = fs.transform(X_train)
	# transform test input data
	X_test_fs = fs.transform(X_test)
	return X_train_fs, X_test_fs, fs

# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=1)
# feature selection
X_train_fs, X_test_fs, fs = select_features(X_train, y_train, X_test)
# fit the model
model = LinearRegression()
model.fit(X_train_fs, y_train)
# evaluate the model
yhat = model.predict(X_test_fs)
# evaluate predictions
mae = mean_absolute_error(y_test, yhat)
print('MAE: %.3f' % mae)

MAE: 0.000


In [136]:
X = df1.drop("genre",axis=1)
y = df1['genre']

In [137]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(X,y)
y_model = model.predict(X)

In [138]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_model)

0.8208959071865937